### ISSUE TITLE
Error when executing the command "sudo ./install.sh -u adc_ads1115" 

### ISSUE THREAD

**Issue by SachiniEMSPE** [Seeed-Studio/pi-hats#2]
Hello, 

I followed the guideline provided to install the Pi Hat. But when i executed the titled command I get the error as: **sudo: ./install.sh: command not found**
I've enabled the I2C of my Raspbian Stretch installed Raspberry Pi 3 B as well. 

Thank you.

**Comment by turmary** [comment]
Hi, 
you need clone this repo,
`git clone https://github.com/Seeed-Studio/pi-hats.git`
then
`cd pi-hats/tools`

**Comment by SachiniEMSPE** [comment]
Hello, 

I was trying with  **`cd pi-hats`** instead of **`cd pi-hats/tools`**  during the installation. 

So this, 
`cd pi-hats/tools`
solved my issue. Thank you for the support :)

**Comment by turmary** [comment]
Will close this issue, please open a new issue if you have further questions.
