### ISSUE TITLE
CAN hat cannot send messages

### ISSUE THREAD

**Issue by JuanAsturias** [Seeed-Studio/pi-hats#4]
Attempting to use cangen can0 -mv there are the following error messages reported by dmesg:

dmesg | grep can 
[    3.643575] mcp25xxfd_can: loading out-of-tree module taints kernel.
[   51.220770] IPv6: ADDRCONF(NETDEV_CHANGE): can0: link becomes ready
[   94.347674] can: controller area network core (rev 20170425 abi 9)
[   94.367269] can: raw protocol (rev 20170425)
[   94.370485] mcp25xxfd spi0.0 can0: CAN Bus error experienced
[   94.370747] mcp25xxfd spi0.0 can0: CAN Bus error experienced

Everything setup according to your instructions, terminators are turned on, power is applied via Raspberry PI's USB port.

**Comment by Pillar1989** [comment]
@JuanAsturias Have you solved your problem ?

**Comment by Pillar1989** [comment]
Closing for now. Happy to reopen if you have further questions.
